version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
  exclusions:
    rules:
      - linters:
          - golint
        text: "should have comment"

formatters:
  enable:
    - gofmt
