services:
  postgres-merchcore:
    image: postgres:18.0
    environment:
      POSTGRES_PASSWORD: "secret"
      POSTGRES_USER:  "postgres"
      POSTGRES_DB: "merchcore"
    ports:
      - "5432:5432"
    volumes:
      - "storehqdata:/var/lib/postgresql/data"
    networks:
      - "merchcorebackend"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis-merchcore:
    image: redis:8.2.0-alpine
    ports:
      - "6379:6379"
    networks:
      - "merchcorebackend"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
  # merchcoreprod:
  #   build::
  #     context: .
  #     dockerfile: Dockerfile 
  #     target: runtime
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - merchcorebackend
  #   secrets:
  #     - db_password
  #   volumes:
  #     - storehqdata:/var/lib/postgresql/data
  #   depends_on:
  #     postgres-merchcore:
  #       condition: service_healthy
  #     redis-merchcore:
  #       condition: service_healthy

volumes:
  storehqdata:
    driver: "local"
 
networks:
  merchcorebackend:
 