services:
  simplebank:
    command:
      - "dlv"
      - "debug"
      - "./cmd/main.go"
      - "--build-flags=-gcflags=all='-N -l'"
      - "--listen=:4000"
      - "--headless=true"
      - "--log=true"
      - "--log-output=debugger,debuglineerr,gdbwire,lldbout,rpc"
      - "--accept-multiclient"
      - "--continue"
      - "--api-version=2"
    ports:
      - "3000:9090"
      - "4000:4000"
  merchcore-app:
    build:
      context: .
      dockerfile: Dockerfile 
      target: dev
    ports:
      - "3000:8080"
    networks:
      - merchcorebackend
    volumes:
      - ./:/app
    depends_on:
      postgres-merchcore:
        condition: service_healthy
      redis-merchcore:
        condition: service_healthy